# Generated by Django 2.2.15 on 2020-08-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='this is sample text edited afterwards'),
            preserve_default=False,
        ),
    ]
